django_2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls")),
    path('user_auth/', include("user_auth.urls")),
]

index/urls.py
from django.urls import path
from .views import home

app_name = "index"

urlpatterns = [
    path("", home, name="home")
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = "user_auth"

urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("register_user", views.register_user, name="register_user"),
    path("logout_user", views.logout_user, name="logout_user"),
]

index/models.py
from django.db import models

# Create your models here.

user_auth/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f"{self.id}"

index/views.py
from django.shortcuts import render


# Create your views here.


def home(request):
    return render(request,"index/home.html")

user_auth/views.py
from django.shortcuts import render, redirect
from .models import MyUser
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def login_user(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        email = request.POST.get("email")
        user = None
        try:
            user = MyUser.objects.get(username=username)
        except:
            messages.error(request, "User does not exist.")
            return redirect("user_auth:login_user")
        if user.email != email:
            messages.error(request, "Email Does not match.")
            return redirect("user_auth:login_user")

        user = authenticate(request, username=username, password=password, email=email)
        if user is not None:
            login(request, user)
            return redirect("index:home")
        else:
            messages.error(request, "Invalid password.")

    return render(request, "user_auth/login.html")


def register_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        user_already_exists = False
        try:
            already_user = MyUser.objects.get(username=username)
        except:
            user_already_exists = True
        if not user_already_exists:
            messages.error(request, "Username already exists.")
            return redirect("user_auth:register_user")

        email_already_exists = False
        try:
            already_email = MyUser.objects.get(email=email)
        except:
            email_already_exists = True
        if not email_already_exists:
            messages.error(request, "Email already exists.")
            return redirect("user_auth:register_user")

        if password == confirm_password:

            user = MyUser.objects.create_user(username=username, email=email, password=password)

            login(request, user)

            return redirect('index:home')
        else:
            messages.error(request, "Passwords do not match.")
            return redirect("user_auth:register_user")

    return render(request, "user_auth/register.html")


def logout_user(request):
    print(request)
    logout(request)
    return redirect("index:home")

index/templates/index/home.html
{% extends 'layout.html' %}

{% block content %}
home
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- CDN -->
    <!-- tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- flow bite -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />

    <!-- data aos -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

</head>
<body class="dark:bg-gray-900 bg-white">

<!-- Navbar -->


<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <a href="{% url 'index:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
  </a>



  <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      {% if user.username %}
      <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>
        <img class="w-8 h-8 rounded-full" src="{% static 'images/pp.jpg' %}" alt="user photo">
      </button>
      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">{{ user.username }}</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{ user.email }}</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
          </li>

          <li>
            <a href="{% url 'user_auth:logout_user' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Logout</a>
          </li>
        </ul>
      </div>
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>

      {% else %}
      <div class="flex space-x-4 ">
          <a href="{% url 'user_auth:login_user' %}">
          <button type="button" class="px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login</button>
              </a>
          <a href="{% url 'user_auth:register_user' %}">
          <button type="button" class="px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Register</button>
              </a>
      </div>

      {% endif %}

  </div>



  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="{% url 'index:home' %}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Home</a>
      </li>
      <li>
        <a href="" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Posts</a>
      </li>
      <li>
        <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
      </li>

    </ul>
  </div>
  </div>
</nav>


<!--block content-->
{% block content %}
{% endblock %}

<!--Footer-->





<!--scripts -->
<!--flow bite -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
<!--data aos -->
 <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
 <script>
 AOS.init();
 </script>
</body>
</html>

templates/user_auth_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
    <style>
        ::-webkit-scrollbar {
            display: none;
        }
    </style>
</head>

<body class="flex flex-col space-y-6 justify-center items-center h-screen bg-white dark:bg-[#111827]  font-mono">
    {% block content %}
    {% endblock %}
</body>

</html>

user_auth/templates/user_auth/change_password.html
{% extends 'user_auth_layout.html' %}

{% block content %}
{% endblock %}

user_auth/templates/user_auth/login.html
{% extends 'user_auth_layout.html' %}

{% block content %}


<div class="flex justify-center">
    {% if messages %}
    {% for message in messages %}
    <div class="flex text-white space-x-4 items-center p-6 justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <span>Warning: {{ message }}</span>
    </div>
    {% endfor %}
    {% endif %}
</div>





<div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-full lg:py-0 w-full">

    <div
        class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700 border border-black">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <div class="flex justify-between items-center">
            <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-3xl dark:text-white">
                Login
            </h1>

            </div>
            <form class="space-y-4 md:space-y-6" method="POST">
                {% csrf_token %}


                <div>
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                    <input type="text" name="username" id="username"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="username" required="">
                </div>

                <div>
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                    <input type="email" name="email" id="email"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="email" required="">
                </div>


                <div>
                    <label for="password"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                    <input type="password" name="password" id="password" placeholder="••••••••"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        required="">
                </div>


                <div class="flex items-center justify-center">
                   <button type="submit" class="px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login</button>

                </div>



                <div class="flex space-x-2 justify-center items-center">
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Don't have an account yet?
                    </p>
                    <a href="{% url 'user_auth:register_user' %}"
                        class="font-medium text-black hover:underline dark:text-white">Register</a>
                </div>
            </form>
        </div>
    </div>
</div>



{% endblock %}

user_auth/templates/user_auth/register.html
{% extends 'user_auth_layout.html' %}

{% block content %}


<div class="flex justify-center">
    {% if messages %}
    {% for message in messages %}
    <div class="flex text-white space-x-4 items-center p-6 justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <span>Warning: {{ message }}</span>
    </div>
    {% endfor %}
    {% endif %}
</div>






<div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-full lg:py-0 w-full">


        <br>
    <div
        class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700
border border-black">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <div class="flex justify-between items-center">
            <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-3xl dark:text-white">
                Register
            </h1>

            </div>


            <form class="space-y-4 md:space-y-6" method="POST">
                {% csrf_token %}
                <div>
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                    <input type="text" name="username" id="username"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="username" required="">
                </div>

                <div>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your
                        email</label>
                    <input type="email" name="email" id="email"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="name@gmail.com" required="">
                </div>

                <div>
                    <label for="password"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                    <input type="password" name="password" id="password"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="••••••••" required="">
                </div>

                <div>
                    <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm
                        Password</label>
                    <input type="password" name="confirm_password" id="confirm_password" placeholder="••••••••"
                        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        required="">
                </div>

                <div class="flex items-center justify-center space-x-2">
                    <button type="submit" class="px-5 py-2.5 text-sm font-medium text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Register</button>
                </div>
                <div class="flex space-x-2 justify-center items-center">
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Already have an account?
                    </p>
                    <a href="{% url 'user_auth:login_user' %}"
                        class="font-medium text-black hover:underline dark:text-white">Login</a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}